### ISSUE TITLE
Flexbox disappeared after build

### ISSUE THREAD

**Issue by linonetwo** [snikas/react-styled-flexbox#2]
I'm using react-styled-flexbox in create-react-app, but after I ran ```yarn build```, every flex box jus disappear, I wonder why?

I'm using styled-components 3.2.3

**Comment by snikas** [comment]
I attempted to repro but cannot.
Here are the steps I took. 

npx create-react-app my-app
cd my-app
'yarn add react-styled-flexbox@1.0.5'
use component in app.js
'yarn build'
'serve build'
